### PR TITLE
Updated catching errors with new return from Teams

### PR DESCRIPTION
**Pull request by tebulrich**
- Microsoft Teams API returns have changed
- Part that checks for errors in this connector updated

### CODE REVIEW

**Comment by tebulrich** [comment]
Dont merge yet

**Comment by JosefB-FA** [comment]
I also noticed this bug and was waiting for your pull request to be merged. Why did you close the request, did Microsoft change something again?

**Comment by tebulrich** [comment]
Yea i got some errors again but i cannot verify them at the moment, since i am not at home. I will check it later (probably not before Wednesday though)

**Comment by JosefB-FA** [comment]
That's fine, thanks for the fix!

**Comment by sebbmeyer** [comment]
@tebeso could you verify you errors?

**Pull request closed without merging**
